Add reviews
KimBogdanov/java-filmorate pull request #4
Opened 2023-12-30 04:51 UTC by laipan009

Описание задачи
В приложении должны появиться отзывы на фильмы. Добавленные отзывы должны иметь рейтинг и несколько дополнительных характеристик.

Характеристики отзыва.

Оценка — полезно/бесполезно.
Тип отзыва — негативный/положительный.
Рейтинг отзыва.

У отзыва имеется рейтинг. При создании отзыва рейтинг равен нулю. Если пользователь оценил отзыв как полезный, это увеличивает его рейтинг на 1. Если как бесполезный, то уменьшает на 1.

Отзывы должны сортироваться по рейтингу полезности.

2023-12-30 05:18 UTC, DesertDogFish commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewDbStorage.java
> +    private final JdbcTemplate jdbcTemplate;
DOWN_RATING + UP_RATING = дубль одного и того же значения - дельты изменения рейтинга

2023-12-30 05:19 UTC, DesertDogFish commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewDbStorage.java
> +        if (idUser < 1) {
removeLikeReview дубль removeDislikeReview

2023-12-30 05:20 UTC, DesertDogFish commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewDbStorage.java
> +        String query = "MERGE INTO estimation_review (user_id, review_id, estimation) " +
likeReview дубль dislikeReview

2023-12-30 05:21 UTC, DesertDogFish commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewDbStorage.java
> +        String query = "SELECT * FROM review WHERE film_id =?";
getReviewsByFilmId - потому что нет никакого All, когда используется счетчик кол-ва записей

2023-12-30 05:21 UTC, DesertDogFish commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewDbStorage.java
> +        System.out.println(reviewId);
getReview - потому как что по id мы и так видим

2023-12-30 05:22 UTC, DesertDogFish commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewDbStorage.java
> +        String query = "DELETE FROM review WHERE review_id=?";
deleteReview - потому как что по id мы и так видим

2023-12-30 05:22 UTC, DesertDogFish commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewDbStorage.java
> +        this.jdbcTemplate = jdbcTemplate;
перемести наверх, плиз

2023-12-30 05:31 UTC, DesertDogFish commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewDbService.java
> +public class ReviewDbService {
ReviewService - потому что сервис не в курсе (и не должен), что он как-то относится к БД

2023-12-30 05:33 UTC, DesertDogFish commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewDbService.java
> +        return reviewStorage.dislikeReview(idReview, idUser);
reviewId, userId - потому что сначала мы пишем верхний уровень, а потом нижний.
так же по сути и ниже removeReviewLike, например, потому что у ревью есть лайк, а не наоборот

2023-12-30 05:47 UTC, DesertDogFish commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewDbStorage.java
> +                .useful(getReviewRank(rs.getInt("review_id")))
не лучший пример взят за основу)))) есть ощущение, что при маппинге эта штука пойдет плодить запросы в БД лишние.

2023-12-30 05:48 UTC, DesertDogFish commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewDbStorage.java
> +        return getReviewById(reviewId)
точно нужно сходить в БД еще раз чтобы узнать то что мы и так знаем?

2023-12-30 05:49 UTC, DesertDogFish approved these changes
не дурно

2023-12-30 10:52 UTC, laipan009 commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewDbStorage.java
> +        String query = "MERGE INTO estimation_review (user_id, review_id, estimation) " +
PUT /reviews/{id}/like/{userId} — пользователь ставит лайк отзыву - likeReview()
PUT /reviews/{id}/dislike/{userId} — пользователь ставит дизлайк отзыву. - dislikeReview()
предлагаешь сделать в одном методе с проверкой наличия записи с соответствующими id и изменять на обратное значение?

2023-12-30 11:13 UTC, laipan009 commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewDbStorage.java
> +        System.out.println(reviewId);
в проекте везде в имя метода включено поле по которому будет выборка и для поддержания единообразия лучше не отличаться) И в дальнейшем при добавлении аналогичных методов с поиском уже по другим критериям будет полезно, если уже по имени будет ясно по какому параметру выборка)

2023-12-30 11:13 UTC, laipan009 commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewDbStorage.java
> +        String query = "DELETE FROM review WHERE review_id=?";
в проекте везде в имя метода включено поле по которому будет выборка и для поддержания единообразия лучше не отличаться) И в дальнейшем при добавлении аналогичных методов с поиском уже по другим критериям будет полезно, если уже по имени будет ясно по какому параметру выборка)

2023-12-30 11:47 UTC, laipan009 commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewDbService.java
> +public class ReviewDbService {
в проекте везде имена классов сервисов имеют в названии Db и для поддержания единообразия лучше не отличаться)

2023-12-30 11:56 UTC, laipan009 commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewDbStorage.java
> +                .useful(getReviewRank(rs.getInt("review_id")))
не особо понял, что имеешь в виду, можешь пояснить и предложить вариант с лучшим* примером?

2023-12-30 12:07 UTC, laipan009 commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewDbStorage.java
> +        return getReviewById(reviewId)
тест постмана "Review update to positive" в теле отправляет "userId": 2, "filmId": 2, а в ответе требует "userId": 1, filmId": 1, то есть эти поля не должны изменяться в запросе PUT и другого способа, как их не обновлять и в ответе отправить актуальные обновленные данные не придумал. Если предложишь, реализуем)

2024-01-06 07:17 UTC, KimBogdanov requested changes

2024-01-06 07:17 UTC, KimBogdanov commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +        System.out.println(id);
Лишняя строчка дублирующая логирование

2024-01-06 07:17 UTC, KimBogdanov commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    @NotBlank(message = "Review description cannot be empty")
@NotBlank подразумевает, что строка не только не может содержать пробелы, но и не может быть null. Следовательно @NotNull можно не писать

2024-01-06 07:17 UTC, KimBogdanov commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewDbService.java
> +    public Integer dislikeReview(int reviewId, int userId) {
Глубоко не вникал, но кажется лучше сделать один метод на изменение рейтинга вместо 2х. Если изменится система рейтинга, то придется редактировать в 2х местах, вместо одного.

2024-01-06 07:17 UTC, KimBogdanov commented on src/main/resources/schema.sql
> +    FOREIGN KEY (film_id) REFERENCES films(film_id) ON DELETE CASCADE
По стилю. Если ссылки на другие таблицы указываешь не у переменных, то вначале объяви все поля, а внизу референсы. По архитектуре  is_boolean выглядит лишней. Этот параметр можно находить налету при запросе отзыва

2024-01-06 14:29 UTC, laipan009 commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewDbService.java
> +    public Integer dislikeReview(int reviewId, int userId) {
в репозитории оставил один метод, по сути они дублировали один и тот же запрос, но в сервис два метода оставил т.к. третий параметр отличает два метода один принимает DOWN_RATING и понижает рейтинг, второй UP_RATING повышает рейтинг.

2024-01-06 14:33 UTC, laipan009 commented on src/main/resources/schema.sql
> +    FOREIGN KEY (film_id) REFERENCES films(film_id) ON DELETE CASCADE
к сожалению, не совсем понимаю, что нужно изменить( не мог бы предложить конкретное решение?))

2024-01-06 16:04 UTC, KimBogdanov approved these changes

2024-01-06 16:04 UTC, merged